"""add token fields to notes

Revision ID: cbad0d08ba69
Revises: 01ea7b0661ea
Create Date: 2026-07-12 20:36:28.429502
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbad0d08ba69'
down_revision: Union[str, None] = '01ea7b0661ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'completion_tokens')
    op.drop_column('notes', 'prompt_tokens')
    # ### end Alembic commands ###
